### ISSUE TITLE
python

### ISSUE THREAD

**Issue by niccanicci** [timsainb/python_spectrograms_and_inversion#3]
Greetings @timsainb ,
is it posibble to run this github on python2.7 and not in Ipython ?
i try to converted it but unable to get the display output...
i appreciate for you to help a newbie  like me

**Comment by timsainb** [comment]
@niccanicci try open up python, and running through the code in the notebook  line by line. It might be easier to read if you follow the blog:
https://timsainb.github.io/spectrograms-mfccs-and-inversion-in-python.html

**Comment by niccanicci** [comment]
@timsainb I already run using jupyter  when i change the audio and re run it back it gave me this error
![screenshot from 2018-02-12 15-55-36](https://user-images.githubusercontent.com/32840015/36087509-af5e9a96-100d-11e8-8f74-d176aa676956.png)

**Comment by timsainb** [comment]
@niccanicci you are most likely using python3. If that is true, and you are using the line:
`step_size = fft_size/16`
try replacing it with:
`step_size = int(fft_size/16)`

**Comment by niccanicci** [comment]
Thank you @timsainb and yes i used python3 to run this
